# Checkov configuration file
# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Skip specific checks (example)
skip-check:
  - CKV_AWS_260   # Ensure no security groups allow ingress from 0.0.0.0:0 to port 80
  - CKV_AWS_23    # SSH is restricted to specific IP addresses, not 0.0.0.0/0
  - CKV_AWS_88    # EC2 instance should not have public IP.
  - CKV_AWS_79    # Ensure Instance Metadata Service Version 1 is not enabled
  - CKV2_AWS_41   # Ensure an IAM role is attached to EC2 instance
  # - CKV_AWS_8   # Ensure all data stored in the Launch configuration EBS is securely encrypted at rest

# Framework to run (can specify multiple)
framework:
  - terraform

# Output formats
output:
  - cli
  - sarif

# Fail on severity (LOW, MEDIUM, HIGH, CRITICAL)
check:
  - HIGH
  - CRITICAL

# Enable compact mode for better readability
compact: true

# Download external modules before scanning
download-external-modules: true

# Quiet mode (reduce output verbosity)
quiet: false

# Enable soft-fail mode (don't fail the build on security issues)
soft-fail: false

# Exclude paths (if needed)
# skip-path:
#   - path/to/exclude