---
- name: Test Ansible Playbook on Localhost
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create a tmp directory
      ansible.builtin.file:
        path: /home/ec2-user/tmp
        state: directory
        mode: '0755'

    - name: Create a test file
      ansible.builtin.copy:
        dest: /home/ec2-user/tmp/ansible_test_file.txt
        content: "This is a test file created by Ansible."
        mode: '0644'

    - name: Install tree package (Linux only)
      become: true
      ansible.builtin.package:
        name: tree
        state: present

    - name: Print a debug message
      ansible.builtin.debug:
        msg: "Playbook executed successfully!"
 