---
- name: Configure Web Servers
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Ensure Nginx is installed
      ansible.builtin.yum:
        name: nginx
        state: present  # Fixed: package-latest

    - name: Ensure Nginx service is running and enabled on boot
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Deploy static website content
      ansible.builtin.copy:
        content: "<h1>Hello from Terraform and Ansible!</h1>"
        dest: /usr/share/nginx/html/index.html
        mode: '0644'  # Fixed: risky-file-permissions
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
