---
- name: Configure Web Servers
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Ensure Nginx is installed
      yum:
        name: nginx
        state: latest

    - name: Ensure Nginx service is running and enabled on boot
      service:
        name: nginx
        state: started
        enabled: true

    - name: Deploy static website content
      copy:
        content: "<h1>Hello from Terraform and Ansible!</h1>"
        dest: /usr/share/nginx/html/index.html
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
